//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeMode
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<int> NameOfDaysID { get; set; }
        public Nullable<int> NameOfMonthID { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public Nullable<int> FiscalWeekNo { get; set; }
    }
}
